### ISSUE TITLE
API error

### ISSUE THREAD

**Issue by todoneunl** [indyhall/mastodon-welcome-bot#3]
My scopes are read, write, follow (I think that are even too much). What can be the problem?

```
https://server.tld:443 "GET /api/v1/accounts/1/followers?limit=80 HTTP/1.1" 403 None
Traceback (most recent call last):
  File "./run.py", line 102, in <module>
    run()
  File "./run.py", line 99, in run
    bot.go()
  File "./run.py", line 70, in go
    users_to_msg = self.get_users()
  File "./run.py", line 51, in get_users
    followers = self.client.account_followers(self.account_id, limit=80)
  File "<decorator-gen-20>", line 2, in account_followers
  File "/home/jeroen/.local/lib/python3.5/site-packages/mastodon/Mastodon.py", line 77, in wrapper
    return function(self, *args, **kwargs)
  File "/home/jeroen/.local/lib/python3.5/site-packages/mastodon/Mastodon.py", line 792, in account_followers
    return self.__api_request('GET', url, params)
  File "/home/jeroen/.local/lib/python3.5/site-packages/mastodon/Mastodon.py", line 2235, in __api_request
    error_msg)
mastodon.Mastodon.MastodonAPIError: ('Mastodon API returned error', 403, 'Forbidden', 'This action is outside the authorized scopes')
```

**Comment by alexknowshtml** [comment]
sorry, this code is unsupported, closing issue.
